
set(SYMBOL_RETRIEVER_SOURCES
        SymbolRetriever.cpp)

add_library(symbol_retriever STATIC ${SYMBOL_RETRIEVER_SOURCES})
target_include_directories(symbol_retriever
        PUBLIC
        $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
)

install(TARGETS symbol_retriever
        EXPORT capiTargets
        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
        RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
        INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)