default:
  before_script:
    - module purge
    - module load gcc/$GCC
    - module load git cmake python/3
  tags:
    - general

variables:
    GIT_STRATEGY: none
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_COMMIT_SHA

stages:
  - download
  - build-deps
  - build
  - test

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never





.job-setup: &job-setup
  parallel:
    matrix:
      - GCC: 10
  variables:
    CAPI_BUILD: build-GCC-$GCC

capi-download:
  stage: download
  variables:
    GIT_STRATEGY: clone
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_COMMIT_SHA
  script:
    - echo 'Done.'

capi-deps:
  <<: *job-setup
  stage: build-deps
  script:
    - ./build_deps.sh

capi-build:
  <<: *job-setup
  stage: build
  script:
    - module use extern/modulefiles/
    - module load llvm/13.0.1-xray-dso
    - cmake -S . -B $CAPI_BUILD -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DSCOREP_SUPPORT=OFF -DENABLE_TALP=OFF
    - cmake --build $CAPI_BUILD --parallel
    - module purge

capi-test-selection:
  <<: *job-setup
  stage: test
  script:
    - cd $CAPI_BUILD
    - ninja capi-selection-test

