variables:
  GIT_STRATEGY: none
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_COMMIT_SHA

default:
  before_script:
    - module purge
    - echo "Value of CAPI_DEPS_MODULEPATH is $CAPI_DEPS_MODULEPATH"
    - |
      if [ -n "$CAPI_DEPS_MODULEPATH" ]; then
        echo "Using dependency modules $CAPI_DEPS_MODULEPATH and adding to $CAPI_ADD_MODULEPATH_VAR"
        #echo "Value of $CAPI_ADD_MODULEPATH_VAR is $(printenv $CAPI_ADD_MODULEPATH_VAR)"
        if [ -n "$CAPI_ADD_MODULEPATH_VAR" ]; then
          export $CAPI_ADD_MODULEPATH_VAR="$CAPI_DEPS_MODULEPATH:$(printenv $CAPI_ADD_MODULEPATH_VAR)"
          echo "New value of $CAPI_ADD_MODULEPATH_VAR: $(printenv $CAPI_ADD_MODULEPATH_VAR)"
        fi
        module use $CAPI_DEPS_MODULEPATH
      fi
    - if [ -z $GCC ]; then GCC=13.1; fi
    - module load gcc/$GCC
    - module load git cmake python/3.9
    - module load openmpi/4.1.6
  tags:
    - general

stages:
  - download
  - build-deps
  - build
  - test
  - install
  - install-test
  - integration-test
  - integration-test-profile

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never


.job-setup: &job-setup
  parallel:
    matrix:
      - GCC: 13
  variables:
    CAPI_BUILD: build-GCC-$GCC
    CAPI_INSTALL: install-GCC-$GCC

capi-download:
  stage: download
  variables:
    GIT_STRATEGY: clone
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_COMMIT_SHA
  script:
    - echo 'Done.'

capi-deps:
  <<: *job-setup
  stage: build-deps
  script:
    - ./build_deps.sh
  rules:
    - if: $CAPI_DEPS_MODULEPATH
      when: never
    - when: always

capi-build:
  <<: *job-setup
  stage: build
  script:
    - |
      if [ -z "$CAPI_DEPS_MODULEPATH" ]; then
        echo "Using locally built dependencies"
        module use extern/modulefiles/
      fi
    - module load llvm/20.1.3
    - module load scorepnoplugin/7.1
    - module load dlb/3.5
    - module load metacg/devel
    - module load flip/devel
    - cmake -S . -B $CAPI_BUILD  -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX="$CAPI_INSTALL" -DCMAKE_C_FLAGS="--gcc-toolchain=$(dirname $(which gcc))/.." -DCMAKE_CXX_FLAGS="--gcc-toolchain=$(dirname $(which gcc))/.." -DTEST_GCC_TOOLCHAIN="$(dirname $(which gcc))/.." -DCMAKE_BUILD_TYPE=Release -DENABLE_EXTRAE=ON -DDLB_DIR=$(dirname $(which dlb))/.. -DSCOREP_DIR=$(which scorep)/../.. -DENABLE_INST_PASSES=ON -DENABLE_TALP=ON -DENABLE_NESMIK=OFF -DENABLE_FLIP=ON -DFlip_DIR="$(dirname $(which flip))/../lib/cmake/flip" -DLLVM_EXTERNAL_LIT=$(which lit) -DCLANG_INCLUDE_DIR="$(clang -print-resource-dir)/include"
    - cmake --build $CAPI_BUILD --parallel
    - module purge

capi-test-symbol-retriever:
  <<: *job-setup
  stage: test
  script:
    - |
      if [ -z "$CAPI_DEPS_MODULEPATH" ]; then
        echo "Using locally built dependencies"
        module use extern/modulefiles/
      fi
    - module load llvm/20.1.3
    - cd $CAPI_BUILD
    - ninja capi-symbol-retriever-test

capi-test-selection:
  <<: *job-setup
  stage: test
  script:
    - |
      if [ -z "$CAPI_DEPS_MODULEPATH" ]; then
        echo "Using locally built dependencies"
        module use extern/modulefiles/
      fi
    - module load llvm/20.1.3
    - module load metacg/devel
    - cd $CAPI_BUILD
    - ninja capi-selection-test

capi-test-passes:
  <<: *job-setup
  stage: test
  script:
    - |
      if [ -z "$CAPI_DEPS_MODULEPATH" ]; then
        echo "Using locally built dependencies"
        module use extern/modulefiles/
      fi
    - module load llvm/20.1.3
    - module load scorepnoplugin/7.1
    - module load papi
    - module load metacg/devel
    - cd $CAPI_BUILD
    - ninja capi-pass-test

capi-test-wrapper:
  <<: *job-setup
  stage: test
  script:
    - |
      if [ -z "$CAPI_DEPS_MODULEPATH" ]; then
        echo "Using locally built dependencies"
        module use extern/modulefiles/
      fi
    - module load llvm/20.1.3
    - module load metacg/devel
    - cd $CAPI_BUILD/test/wrapper
    - make clean && make all
    - ./main.exe

capi-install:
  <<: *job-setup
  stage: install
  script:
    - |
      if [ -z "$CAPI_DEPS_MODULEPATH" ]; then
        echo "Using locally built dependencies"
        module use extern/modulefiles/
      fi
    - module load llvm/20.1.3
    - module load scorepnoplugin/7.1
    - module load dlb/3.5
    - module load metacg/devel
    - cmake --install $CAPI_BUILD

capi-test-install:
  <<: *job-setup
  stage: install-test
  script:
    - |
      if [ -z "$CAPI_DEPS_MODULEPATH" ]; then
        echo "Using locally built dependencies"
        module use extern/modulefiles/
      fi
    - module load llvm/20.1.3
    - module load metacg/devel
    - cd $CAPI_BUILD
    - ctest -R "capi_test_install_configure" --verbose
    - ctest -R "capi_test_install_build" --verbose
    - ctest -R "capi_test_install_run" --verbose

capi-build-example:
  <<: *job-setup
  stage: integration-test
  script:
    - |
      if [ -z "$CAPI_DEPS_MODULEPATH" ]; then
        echo "Using locally built dependencies"
        module use extern/modulefiles/
      fi    
    - module load llvm/20.1.3
    - module load scorepnoplugin/7.1
    - module load dlb/3.5
    - module load metacg/devel
    - cd $CAPI_BUILD/examples/lulesh
    - make clean
    - make LDFLAGS="-O3 --gcc-toolchain=$(dirname $(which gcc))/.." VARIANT=scorep
    - make LDFLAGS="-O3 --gcc-toolchain=$(dirname $(which gcc))/.." VARIANT=extrae
    - cd ../AMG2013 
    - make veryclean
    - make INCLUDE_LFLAGS="-lm  -fopenmp --gcc-toolchain=$(dirname $(which gcc))/.." all

capi-test-example-selection:
  <<: *job-setup
  stage: integration-test
  script:
    - |
      if [ -z "$CAPI_DEPS_MODULEPATH" ]; then
        echo "Using locally built dependencies"
        module use extern/modulefiles/
      fi
    - module load llvm/20.1.3
    - module load scorepnoplugin/7.1
    - module load dlb/3.5
    - module load metacg/devel
    - module load flip/devel
    - cd $CAPI_BUILD/test/integration
    - ./runTestCases -tc=input

capi-test-example-run:
  <<: *job-setup
  stage: integration-test-profile
  script:
    - |
      if [ -z "$CAPI_DEPS_MODULEPATH" ]; then
        echo "Using locally built dependencies"
        module use extern/modulefiles/
      fi
    - module load llvm/20.1.3
    - module load scorepnoplugin/7.1
    - module load dlb/3.5
    - cd $CAPI_BUILD/examples/lulesh
    - cp ../../test/integration/input/lulesh/lulesh_full.compute.gtjson lulesh_test_filter.json
    - CAPI_OPTIONS="--config lulesh_test_filter.json" SCOREP_OVERWRITE_EXPERIMENT_DIRECTORY=true SCOREP_EXPERIMENT_DIRECTORY="scorep-test-profile" ./lulesh2.0_scorep -s 10
    - num_usr=$(scorep-score -r scorep-test-profile/profile.cubex | grep USR | wc -l)
    - | 
      if [[ $num_usr != 10 ]]; then 
        echo "Expected 10 USR regions but got $num_usr"
        exit 1
      fi

