#include "SelectorRegistry.h"
#include <unordered_map>
#include <vector>

#define SELECTOR_DOC(selectorName, selectorType, parameterLabels, parameterTypes, example, selectorDesc, numInputs) \
    capi::SelectorDoc(#selectorName, selectorType, parameterLabels, parameterTypes, example, selectorDesc, numInputs)

inline const auto& getAllSelectorDocs() {
    static std::vector<capi::SelectorDoc> selectorDocs = {
        SELECTOR_DOC(by_name,
                     capi::SelectorType::DEFAULT,
                     (std::vector<std::string>{"regex string"}),
                     (std::vector<std::string>{"string"}),
                     "by_name(\"foo.*\")",
                     "Selects functions with names starting with \"foo\".","1"),
        SELECTOR_DOC(by_path,
                     capi::SelectorType::DEFAULT,
                     (std::vector<std::string>{"regex string"}),
                     (std::vector<std::string>{"string"}),
                     "by_path(\"foo/.*\")",
                     "Selects functions contained in directory \"foo\".","1"),
        SELECTOR_DOC(inline_specified,
                     capi::SelectorType::DEFAULT,
                     {},
                     {},
                     "inline_specified",
                     "Selects functions marked as inline.","1"),
        SELECTOR_DOC(on_call_path_to,
                     capi::SelectorType::DEFAULT,
                     {},
                     {},
                     "by_name(\"foo\") \\|> on_call_path_to",
                     "Selects functions in the call chain to function \"foo\".","1"),
        SELECTOR_DOC(on_call_path_from,
                     capi::SelectorType::DEFAULT,
                     {},
                     {},
                     "by_name(\"foo\") \\|> on_call_path_from",
                     "Selects functions in the call chain from function \"foo\".","1"),
        SELECTOR_DOC(in_system_header,
                     capi::SelectorType::DEFAULT,
                     {},
                     {},
                     "in_system_header",
                     "Selects functions defined in system headers.","1"),
        SELECTOR_DOC(contains_unresolved_calls,
                     capi::SelectorType::DEFAULT,
                     {},
                     {},
                     "contains_unresolved_calls",
                     "Selects functions containing calls to unknown target functions.","1"),
        SELECTOR_DOC(join,
                     capi::SelectorType::DEFAULT,
                     {},
                     {},
                     "[%A, %B] \\|> join or %A \\| %B",
                     "Union of the two input sets.","2"),
        SELECTOR_DOC(intersect,
                     capi::SelectorType::DEFAULT,
                     {},
                     {},
                     "[%A, %B] \\|> intersect or %A & %B",
                     "Intersection of the two input sets.","2"),
        SELECTOR_DOC(subtract,
                     capi::SelectorType::DEFAULT,
                     {},
                     {},
                     "[%A, %B] \\|> subtract or %A - %B",
                     "Difference of the two input sets.","2"),
        SELECTOR_DOC(coarse,
                     capi::SelectorType::DEFAULT,
                     {},
                     {},
                     "[%A, %B] \\|> coarse",
                     "Filter out functions that have a single caller and callee, unless they are included in B.","1 or 2"),
        SELECTOR_DOC(min_call_depth,
                     capi::SelectorType::DEFAULT,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "%A \\|> min_call_depth(\"<=\", 3)",
                     "Selects functions that are at most 3 calls away from a root node.","1"),
        SELECTOR_DOC(flops,
                     capi::SelectorType::DEFAULT,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "%A \\|> flops(\">=\", 10)",
                     "Selects functions with at least 10 floating point operations.","1"),
        SELECTOR_DOC(memops,
                     capi::SelectorType::DEFAULT,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "%A \\|> memops(\">=\", 10)",
                     "Selects functions with at least 10 memory operations.","1"),
        SELECTOR_DOC(loop_depth,
                     capi::SelectorType::DEFAULT,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "%A \\|> loop_depth(\"=\", 2)",
                     "Selects functions containing loop nests of depth 2.","1"),
        SELECTOR_DOC(inclusive_statement_count,
                     capi::SelectorType::DEFAULT,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "%A \\|> inclusive_statement_count(\">\", 100)",
                     "Selects functions with an inclusive statement count (statements in reachable sub-graph) > 100.","1"),
        SELECTOR_DOC(common_caller,
                     capi::SelectorType::DEFAULT,
                     (std::vector<std::string>{"heuristic parameter"}),
                     {},
                     "[by_name(\"foo\"), by_name(\"bar\")] \\|> common_caller(1)",
                     "Common caller selection with max. LCA-Dist 1","2"),
        SELECTOR_DOC(common_caller_distinct,
                     capi::SelectorType::DEFAULT,
                     (std::vector<std::string>{"heuristic parameter"}),
                     {},
                      "[by_name(\"foo\"), by_name(\"bar\")] \\|> common_caller_distinct(1)",
                      "Common caller selection (distinct heuristic) with max. LCA-Dist 1.","2"),
        SELECTOR_DOC(common_caller_partial,
                     capi::SelectorType::DEFAULT,
                     (std::vector<std::string>{"heuristic parameter"}),
                     {},
                      "[by_name(\"foo\"), by_name(\"bar\")] \\|> common_caller_partial(1)",
                      "Common caller selection (partial heuristic) with max. LCA-Dist 1.","2"),
        SELECTOR_DOC(has_talp_metrics,
                     capi::SelectorType::TALP,
                     {},
                     {},
                     "has_talp_metrics",
                     "Selects the subset of functions that has TALP metrics attached.","1"),
        SELECTOR_DOC(talp_cycles,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_cycles(\">\", 1000)",
                     "Selection based on number of elapsed cycles.","1"),
        SELECTOR_DOC(talp_instructions,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_instructions(\">\", 500000)",
                     "Selection based on number of executed instructions.","1"),
        SELECTOR_DOC(talp_measurements,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_measurements(\">\", 5)",
                     "Selection based on number of times a node was measured.","1"),
        SELECTOR_DOC(talp_mpi_calls,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_mpi_calls(\">=\", 10)",
                     "Selection based on number of MPI calls.","1"),
        SELECTOR_DOC(talp_omp_parallels,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_omp_parallels(\">=\", 10)",
                     "Selection based on number of encountered OpenMP parallel regions.","1"),
        SELECTOR_DOC(talp_omp_tasks,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_omp_tasks(\">=\", 10)",
                     "Selection based on number of encountered OpenMP tasks.","1"),
        SELECTOR_DOC(talp_gpu_runtime_calls,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_gpu_runtime_calls(\"<\", 60)",
                     "Selection based on number of CUDA/HIP runtime calls.","1"),
        SELECTOR_DOC(talp_elapsed_time,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_elapsed_time(\"<\", 2.0e6)",
                     "Selection based on total elapsed time in nanoseconds.","1"),
        SELECTOR_DOC(talp_useful_time,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_useful_time(\"<\", 2.0e6)",
                     "Selection based on total useful time in nanoseconds.","1"),
        SELECTOR_DOC(talp_parallel_efficiency,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_parallel_efficiency(\"<\", 0.8)",
                     "Selection based on overall parallel efficiency (ratio between 0 and 1).","1"),
        SELECTOR_DOC(talp_mpi_parallel_efficiency,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_mpi_parallel_efficiency(\"<\", 0.9)",
                     "Selection based on MPI parallel efficiency (ratio between 0 and 1).","1"),
        SELECTOR_DOC(talp_mpi_comm_efficiency,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_mpi_comm_efficiency(\"<\", 0.85)",
                     "Selection based on MPI communication efficiency.","1"),
        SELECTOR_DOC(talp_mpi_load_balance,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_mpi_load_balance(\"<\", 0.95)",
                     "Selection based on MPI load balance efficiency.","1"),
        SELECTOR_DOC(talp_mpi_load_balance_in,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_mpi_load_balance_in(\"<\", 0.9)",
                     "Selection based on MPI intra-node load balance.","1"),
        SELECTOR_DOC(talp_mpi_load_balance_out,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_mpi_load_balance_out(\"<\", 0.9)",
                     "Selection based on MPI inter-node load balance.","1"),
        SELECTOR_DOC(talp_omp_parallel_efficiency,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_omp_parallel_efficiency(\"<\", 0.5)",
                     "Selection based on OpenMP parallel efficiency (ratio between 0 and 1).","1"),
        SELECTOR_DOC(talp_omp_load_balance,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_omp_load_balance(\"<\", 0.5)",
                     "Selection based on OpenMP load balance.","1"),
        SELECTOR_DOC(talp_omp_scheduling_efficiency,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_omp_scheduling_efficiency(\"<\", 0.5)",
                     "Selection based on OpenMP scheduling efficiency.","1"),
        SELECTOR_DOC(talp_omp_serialization_efficiency,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_omp_serialization_efficiency(\"<\", 0.5)",
                     "Selection based on OpenMP serialization efficiency.","1"),
        SELECTOR_DOC(talp_device_offload_efficiency,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_device_offload_efficiency(\"<\", 0.5)",
                     "Selection based on GPU offload efficiency.","1"),
        SELECTOR_DOC(talp_gpu_parallel_efficiency,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_gpu_parallel_efficiency(\"<\", 0.5)",
                     "Selection based on GPU parallel efficiency (ratio between 0 and 1).","1"),
        SELECTOR_DOC(talp_gpu_comm_efficiency,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_gpu_comm_efficiency(\"<\", 0.5)",
                     "Selection based on GPU communication efficiency.","1"),
        SELECTOR_DOC(talp_gpu_orch_efficiency,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_gpu_orch_efficiency(\"<\", 0.5)",
                     "Selection based on GPU orchestration efficiency.","1"),
        SELECTOR_DOC(talp_dyn_filtered,
                     capi::SelectorType::TALP,
                     {},
                     {},
                     "talp_dyn_filtered",
                     "Selects functions filtered dynamically during TALP run.","1"),
        SELECTOR_DOC(talp_avg_region_duration,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_avg_region_duration(\"<\", 1e6)",
                     "Selection based on average elapsed nanoseconds per region invocation.","1"),
        SELECTOR_DOC(talp_avg_ipc,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_avg_ipc(\"<\", 0.5)",
                     "Selection based on average useful instructions per cycle value.","1"),
        SELECTOR_DOC(talp_avg_freq,
                     capi::SelectorType::TALP,
                     (std::vector<std::string>{"comp. operator", "threshold"}),
                     (std::vector<std::string>{"string", "number"}),
                     "talp_avg_freq(\"<\", 1e9)",
                     "Selection based on average useful frequency in Hertz.", "1")
    };
  return selectorDocs;
}

inline const capi::SelectorDoc& getSelectorDoc(std::string_view name) {
    const auto& docs = getAllSelectorDocs();

    auto it = std::find_if(
        docs.begin(),
        docs.end(),
        [&](const auto& doc) {
            return doc.name == name;
        }
    );

    if (it == docs.end()) {
        throw std::runtime_error(
            "Selector documentation not found for: " +
            std::string(name)
        );
    }

    return *it;
}
